TOP_PRODUCTS_QUERY = """
SELECT
    p.PRODUCT_NAME,
    COUNT(*) AS TIMES_PURCHASED,
    SUM(op.REORDERED) AS TIMES_REORDERED
FROM QUERYMIND.ORDER_PRODUCTS_PRIOR op
JOIN QUERYMIND.PRODUCTS p
    ON op.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_NAME
ORDER BY TIMES_REORDERED DESC
LIMIT 10
"""